=== AdventurePHP/code/extensions/apfelsms/data/apfelsms.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT apfelsms (page)*>

<!-- page -->
<!ELEMENT page (title|navTitle|page|pageDec|css|js)*>
<!ATTLIST page id ID #REQUIRED>
<!ELEMENT namespace (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT navTitle (#PCDATA)>
<!ELEMENT css (#PCDATA)>
<!ATTLIST css key CDATA #IMPLIED>
<!ELEMENT js (#PCDATA)>

<!--pageDec -->
<!ELEMENT pageDec (referencedPageId|requestParam|externalURL|providerServiceName|providerServiceNamespace|permissionName|anchor)*>
<!ATTLIST pageDec type CDATA #REQUIRED>

<!-- pageDec type "alias" -->
<!ELEMENT referencedPageId (#PCDATA)>

<!-- pageDec type "request" and "parentRequest" -->
<!ELEMENT requestParam (#PCDATA)>
<!ATTLIST requestParam key CDATA #REQUIRED>

<!-- pageDec type "externalURL" -->
<!ELEMENT externalURL (#PCDATA)>

<!-- pageDec type "accessCtrl" -->
<!ELEMENT providerServiceName (#PCDATA)>
<!ELEMENT providerServiceNamespace (#PCDATA)>
<!ELEMENT permissionName (#PCDATA)>

<!-- pageDec type "anchor" and "parentAnchor" -->
<!ELEMENT anchor (#PCDATA)>

=== AdventurePHP/code/extensions/apfelsms/data/apfelsms.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE apfelsms SYSTEM "apfelsms.dtd">
<apfelsms>


   <!-- Main navigation and page tree -->
   <page id="index">
      <title>Herzlich Willkommen!</title>
      <navTitle>Home</navTitle>
   </page>
   <page id="news">
      <title>Aktuelles</title>
      <page id="news-archive">
         <title>News-Archiv</title>
         <css>/styles/news.css</css>
         <pageDec type="alias">
            <referencedPageId>news</referencedPageId>
         </pageDec>
         <pageDec type="request">
            <requestParam key="archive">show</requestParam>
         </pageDec>
      </page>
   </page>
   <page id="about">
      <title>Ãœber uns</title>
   </page>
   <page id="contact">
      <title>Kontakt</title>
      <js>/scripts/jQuery.js</js>
      <js>/scripts/checkContactForm.js</js>
   </page>
   <page id="impress">
      <title>Impressum &amp; Disclaimer</title>
      <navTitle>Impressum</navTitle>
   </page>


   <!-- Pages which does not occur in the navigation -->
   <page id="error404">
      <title>404 - Nicht gefunden!</title>
      <pageDec type="hidden" />
   </page>
   <page id="error403">
      <title>403 - Kein Zugriff!</title>
      <pageDec type="hidden" />
   </page>


   <!-- Additional navigation tree -->
   <page id="footer-nav">
      <pageDec type="hidden" />

      <page id="footer-index">
         <pageDec type="redirect">
            <referencedPageId>index</referencedPageId>
         </pageDec>
      </page>
      <page id="sitemap">
         <title>Sitemap</title>
      </page>
      <page id="footer-contact">
         <pageDec type="redirect">
            <referencedPageId>contact</referencedPageId>
         </pageDec>
      </page>
      <page id="footer-impress">
         <pageDec type="redirect">
            <referencedPageId>impress</referencedPageId>
         </pageDec>
      </page>
   </page>

   <page id="apf-community">
      <pageDec type="hidden" />
      <pageDec type="externalURL">
         <externalURL>http://forum.adventure-php-framework.org</externalURL>
      </pageDec>
   </page>

</apfelsms>
